service: poc-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${opt:stage, self:provider.stage}-*
plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    default:
      enabled: true
      role: IamRoleLambdaExecution
      events:
        - schedule: cron(0/5 8-23 ? * MON-FRI *)
functions:
  app:
    handler: app/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    warmup:
      default:
        enabled: true
